@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="{{asset('css/confirm.css')}}">
@endsection

@section('content')
<div>
    <div>
        <div>
            <h2>Confirm</h2>
        </div>
        <div>
            <form class="" action="/thanks" method="POST">
                @csrf
                <table>
                    <tr>
                        <th>お名前</th>
                        <td>{{$contact['last_name']}}&emsp;{{$contact['first_name']}}</td>
                    </tr>
                    <tr>
                        <th>性別</th>
                        <td>{{$contact['gender']}}</td>
                    </tr>
                    <tr>
                        <th>メールアドレス</th>
                        <td>{{$contact['email']}}</td>
                    </tr>
                    <tr>
                        <th>電話番号</th>
                        <td>{{$contact['tel1']}}{{$contact['tel2']}}{{$contact['tel3']}}</td>
                    </tr>
                    <tr>
                        <th>住所</th>
                        <td>{{$contact['address']}}</td>
                    </tr>
                    <tr>
                        <th>建物名</th>
                        <td>{{$contact['building']}}</td>
                    </tr>
                    <tr>
                        <th>お問い合わせの種類</th>
                        <td>{{$contact['category_content']}}</td>
                    </tr>
                    <tr>
                        <th>お問い合わせ内容</th>
                        <td>{{$contact['detail']}}</td>
                    </tr>
                Ï</table>
                <div>
                    <button>送信</button>
                </div>
            </form>
            <button>修正</button>
        </div>
    </div>
</div>
@endsection
